# Generated by Django 5.0.1 on 2025-11-29 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("team", "Team"),
                            ("product", "Product"),
                        ],
                        default="default",
                        max_length=50,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        default="global",
                        help_text='User-provided context name (e.g., "billing", "auth", "global")',
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_assets",
                        to="authentication.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "config_assets",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfigObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("kv", "Key-Value"),
                            ("text", "Text"),
                            ("file", "File"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objects",
                        to="config_assets.configasset",
                    ),
                ),
            ],
            options={
                "db_table": "config_objects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConfigValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("stage", "Stage"),
                            ("prod", "Production"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                            ("reference", "Reference"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("value_string", models.TextField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="config_assets.configobject",
                    ),
                ),
                (
                    "value_reference",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to another config object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referenced_by",
                        to="config_assets.configobject",
                    ),
                ),
            ],
            options={
                "db_table": "config_values",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ConfigVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("stage", "Stage"),
                            ("prod", "Production"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "value_snapshot",
                    models.JSONField(
                        help_text="Complete snapshot of config at this version"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("change_summary", models.TextField(blank=True)),
                (
                    "config_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="config_assets.configobject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "config_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddIndex(
            model_name="configasset",
            index=models.Index(
                fields=["tenant", "context_type"], name="config_asse_tenant__9a0afc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configasset",
            index=models.Index(
                fields=["tenant", "context"], name="config_asse_tenant__fb8b8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configasset",
            index=models.Index(
                fields=["tenant", "name"], name="config_asse_tenant__1db47d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="configasset",
            unique_together={("tenant", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="configobject",
            unique_together={("asset", "name")},
        ),
        migrations.AddIndex(
            model_name="configvalue",
            index=models.Index(
                fields=["config_object", "environment"],
                name="config_valu_config__9cebe3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="configvalue",
            unique_together={("config_object", "environment", "key")},
        ),
        migrations.AddIndex(
            model_name="configversion",
            index=models.Index(
                fields=["config_object", "environment", "-version_number"],
                name="config_vers_config__087dc9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="configversion",
            unique_together={("config_object", "environment", "version_number")},
        ),
    ]
