# Generated by Django 5.2.8 on 2025-11-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config_assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configobject",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_objects",
                to="config_assets.configasset",
            ),
        ),
    ]
