# Generated by Django 5.2.8 on 2025-12-08 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_user_managers"),
        ("config_assets", "0003_auto_20251208_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="configvalue",
            name="value_encrypted",
            field=models.BinaryField(
                blank=True, help_text="Encrypted value (AES-GCM)", null=True
            ),
        ),
        migrations.CreateModel(
            name="EncryptionKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("encrypted_dek", models.BinaryField(help_text="DEK encrypted by KEK")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_keys",
                        to="authentication.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "encryption_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="configvalue",
            name="encryption_key",
            field=models.ForeignKey(
                blank=True,
                help_text="Key used to encrypt this value",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encrypted_values",
                to="config_assets.encryptionkey",
            ),
        ),
    ]
