# Generated by Django 5.2.8 on 2025-11-30 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_keys", "0002_initial"),
        ("config_assets", "0002_alter_configobject_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, key is scoped to this asset only",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="config_assets.configasset",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="scope",
            field=models.CharField(
                choices=[("tenant", "Tenant-wide"), ("asset", "Asset-specific")],
                default="tenant",
                help_text="Scope of the API key",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key_prefix",
            field=models.CharField(max_length=16),
        ),
    ]
