# Generated by Django 5.2.8 on 2025-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_keys", "0003_apikey_asset_apikey_scope_alter_apikey_key_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="environment",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("stage", "Stage"),
                    ("prod", "Production"),
                ],
                default="local",
                help_text="Environment this key is scoped to",
                max_length=20,
            ),
        ),
    ]
