# Generated by Django 5.2.8 on 2025-12-08 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("authentication", "0006_alter_user_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="hash",
            field=models.CharField(
                editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="previous_hash",
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["hash"], name="audit_activ_hash_9ac4a5_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["previous_hash"], name="audit_activ_previou_aaa4b4_idx"
            ),
        ),
    ]
