# Generated by Django 5.2.8 on 2025-11-30 14:42

from django.db import migrations

def populate_memberships(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    TenantMembership = apps.get_model('authentication', 'TenantMembership')

    for user in User.objects.all():
        # Create membership if it doesn't exist
        if not TenantMembership.objects.filter(user=user, tenant=user.tenant).exists():
            TenantMembership.objects.create(
                user=user,
                tenant=user.tenant,
                role=user.role
            )
        
        # Set current_tenant
        user.current_tenant = user.tenant
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_user_current_tenant_tenantinvitation_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_memberships, reverse_code=migrations.RunPython.noop),
    ]
