# Generated by Django 5.2.8 on 2025-11-30 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_auto_20251130_1442"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Context type name (e.g., team, product)",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Category for grouping (e.g., team, product)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_types",
                        to="authentication.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "context_types",
                "ordering": ["type", "category"],
                "unique_together": {("tenant", "type", "category")},
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., Development)", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., dev)", max_length=100
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="authentication.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "environments",
                "ordering": ["order", "name"],
                "unique_together": {("tenant", "slug")},
            },
        ),
    ]
