# Generated by Django 5.2.8 on 2025-12-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_contexttype_environment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contexttype",
            name="category",
            field=models.CharField(
                help_text="Category for grouping (e.g., specific team name or product name)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="contexttype",
            name="type",
            field=models.CharField(
                choices=[("product", "Product"), ("team", "Team")],
                help_text="Context type name (product or team)",
                max_length=100,
            ),
        ),
    ]
