# Generated by Django 5.2.8 on 2025-12-01 03:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_contexttype_category_alter_contexttype_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
